// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObligatorioP3.Models;

#nullable disable

namespace ObligatorioP3.Migrations
{
    [DbContext(typeof(ObligatorioContext))]
    [Migration("20240607185131_AddEmpleadoActivo")]
    partial class AddEmpleadoActivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObligatorioP3.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Cliente__3214EC27E645851C");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Clima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionClima")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeOnly?>("Fecha")
                        .HasColumnType("time");

                    b.Property<string>("Temperatura")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Clima__3214EC27D9248E40");

                    b.ToTable("Clima", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Empleado__3214EC27B248631C");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.FotoMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("Foto")
                        .HasColumnType("int");

                    b.HasKey("MenuId")
                        .HasName("PK__FotoMenu__C99ED230FEDE4F1F");

                    b.ToTable("FotoMenu", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.FotoRestaurante", b =>
                {
                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.Property<int?>("Foto")
                        .HasColumnType("int");

                    b.HasKey("RestauranteId")
                        .HasName("PK__FotoRest__AAF3667B0EBE0B7E");

                    b.ToTable("FotoRestaurante", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.FotoUsuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("Foto")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId")
                        .HasName("PK__FotoUsua__2B3DE7B874FE19B2");

                    b.ToTable("FotoUsuario", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Login", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombrePlato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("numeric(14, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Menu__3214EC27A8DA0DF5");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.Property<int?>("Restauranteid")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Mesa__3214EC278A878A88");

                    b.HasIndex("Restauranteid");

                    b.HasIndex(new[] { "NumeroMesa", "Restauranteid" }, "ukMesaRestaurante")
                        .IsUnique()
                        .HasFilter("[Restauranteid] IS NOT NULL");

                    b.ToTable("Mesa", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("numeric(20, 2)");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(20, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Orden__3214EC273393CBBB");

                    b.HasIndex("ReservaId");

                    b.ToTable("Orden", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.OrdenDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("int");

                    b.Property<int?>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrdenDet__3214EC27607CAC7D");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("OrdenDetalle", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("numeric(14, 2)");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int")
                        .HasColumnName("ReservaID");

                    b.HasKey("Id")
                        .HasName("PK__Pago__3214EC27A9198358");

                    b.HasIndex("ReservaId");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Clienteid")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int");

                    b.Property<int?>("RestauranteId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reserva__3214EC27B66A03C9");

                    b.HasIndex("Clienteid");

                    b.HasIndex("MesaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reseña__3214EC2717D3C5C7");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Reseña", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Restaura__3214EC27F8AC1771");

                    b.ToTable("Restaurante", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__3214EC27A5486A8A");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ObligatorioP3.Models.Cliente", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Usuario", "IdNavigation")
                        .WithOne("Cliente")
                        .HasForeignKey("ObligatorioP3.Models.Cliente", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__Cliente__ID__3C69FB99");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Empleado", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Usuario", "IdNavigation")
                        .WithOne("Empleado")
                        .HasForeignKey("ObligatorioP3.Models.Empleado", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__Empleado__ID__403A8C7D");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("ObligatorioP3.Models.FotoMenu", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Menu", "Menu")
                        .WithOne("FotoMenu")
                        .HasForeignKey("ObligatorioP3.Models.FotoMenu", "MenuId")
                        .IsRequired()
                        .HasConstraintName("FK__FotoMenu__MenuId__4AB81AF0");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ObligatorioP3.Models.FotoRestaurante", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Restaurante", "Restaurante")
                        .WithOne("FotoRestaurante")
                        .HasForeignKey("ObligatorioP3.Models.FotoRestaurante", "RestauranteId")
                        .IsRequired()
                        .HasConstraintName("FK__FotoResta__Resta__45F365D3");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioP3.Models.FotoUsuario", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Usuario", "Usuario")
                        .WithOne("FotoUsuario")
                        .HasForeignKey("ObligatorioP3.Models.FotoUsuario", "UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__FotoUsuar__Usuar__398D8EEE");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Mesa", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Restaurante", "Restaurante")
                        .WithMany("Mesas")
                        .HasForeignKey("Restauranteid")
                        .HasConstraintName("FK__Mesa__Restaurant__4E88ABD4");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Orden", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Reserva", "Reserva")
                        .WithMany("Ordens")
                        .HasForeignKey("ReservaId")
                        .HasConstraintName("FK__Orden__ReservaId__5CD6CB2B");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ObligatorioP3.Models.OrdenDetalle", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Menu", "Menu")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("FK__OrdenDeta__MenuI__60A75C0F");

                    b.HasOne("ObligatorioP3.Models.Orden", "Orden")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("OrdenId")
                        .HasConstraintName("FK__OrdenDeta__Orden__5FB337D6");

                    b.HasOne("ObligatorioP3.Models.Restaurante", "Restaurante")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("RestauranteId")
                        .HasConstraintName("FK__OrdenDeta__Resta__619B8048");

                    b.Navigation("Menu");

                    b.Navigation("Orden");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Pago", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId")
                        .HasConstraintName("FK__Pago__ReservaID__59FA5E80");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Reserva", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("Clienteid")
                        .HasConstraintName("FK__Reserva__Cliente__5165187F");

                    b.HasOne("ObligatorioP3.Models.Mesa", "Mesa")
                        .WithMany("Reservas")
                        .HasForeignKey("MesaId")
                        .HasConstraintName("FK__Reserva__MesaId__534D60F1");

                    b.HasOne("ObligatorioP3.Models.Restaurante", "Restaurante")
                        .WithMany("Reservas")
                        .HasForeignKey("RestauranteId")
                        .HasConstraintName("FK__Reserva__Restaur__52593CB8");

                    b.Navigation("Cliente");

                    b.Navigation("Mesa");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Reseña", b =>
                {
                    b.HasOne("ObligatorioP3.Models.Cliente", "Cliente")
                        .WithMany("Reseñas")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK__Reseña__ClienteI__571DF1D5");

                    b.HasOne("ObligatorioP3.Models.Reserva", "Reserva")
                        .WithMany("Reseñas")
                        .HasForeignKey("ReservaId")
                        .HasConstraintName("FK__Reseña__ReservaI__5629CD9C");

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Menu", b =>
                {
                    b.Navigation("FotoMenu");

                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Mesa", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Orden", b =>
                {
                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Reserva", b =>
                {
                    b.Navigation("Ordens");

                    b.Navigation("Pagos");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Restaurante", b =>
                {
                    b.Navigation("FotoRestaurante");

                    b.Navigation("Mesas");

                    b.Navigation("OrdenDetalles");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ObligatorioP3.Models.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("FotoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
